### ISSUE TITLE
[Feature] Add configurable Build config

### ISSUE THREAD

**Issue by conradkirschner** [aerokube/images#249] opened 2020-06-16 10:00 UTC
I was thinking about a config file that is like the browsers.json

- predefined values for building
- adding own docker registry to push

**Comment by vania-pooh** [comment] 2020-06-16 18:11
We are now working on automated CI for building images from these sources, so probably this will be implemented soon.

**Comment by M4nouel** [comment] 2020-07-15 12:03
Hi,

Before we go to the Moon, we're using a Selenoid Cluster (GGR+Selenoid).
But to fullfil our base requirements, we need an firefox ESR selenoid image.
So i yet rebuild your selenoid firefox image to be able to get Selenoid running our personalised firefox ESR,
but i would like to know if you were interresting in adding some extra features often important in company environnement like :

* ability to build browser selenoid images behind corporate proxy
* Firefox ESR PPA support
* limitation-less download of tiers depandencies
  (e.g getting geckodriver through github API require to have an nomminative account on github
  and to do the call as a logged in user in order to be sure to not be kicked off by the API limitations)

Let me know if you're interresting in, i could share some basic workaround i implemented in order to prepare to build through jenkins, and contribute for better implementation of these feature if you want.

Cheers !

**Comment by vania-pooh** [comment] 2020-07-15 12:06
@M4nouel feel free to share your ideas. Btw, Firefox ESR seems to be already implemented in these source files.

**Comment by M4nouel** [comment] 2020-07-15 15:09
**Thanks for the quick answer @vania-pooh.**

* I didn't see ESR PPA support had been released in 6.2 while i was struggling adding it in the 6.1 😳. Thanks for the info.
* I can deal with the proxy stuff using Linux variables environment...
* **But the github API requires to be logged in to have a reasonable [request rate limit](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting). So currently, our builds fails randomly.
These failures are due to the preliminary API calls to get the final download link (e.g https://github.com/aerokube/selenoid-images/blob/1021474b1b9d442f67a6ea48ca7ae385e83f9d66/selenium/build.sh#L41).
But according to the [Github docs](https://docs.github.com/en/github/administering-a-repository/linking-to-releases), the format of the final download links seems to follow a logic and are therefore pretty stable.** 

**So can i suggest to**
* **directly call, for example, this link :**
```https://github.com/mozilla/geckodriver/releases/download/$tag/geckodriver-$tag-linux64.tar.gz```
**instead of this one :**
```https://api.github.com/repos/mozilla/geckodriver/releases/tags/$tag``` 
* **Or add ability to perform authenticated requests to github API ?**

**Comment by vania-pooh** [comment] 2020-07-15 15:20
@M4nouel yes, doing direct calls would be better. Feel free to send PR with proxy and direct calls. Let's do this one by one and start with direct calls change.

**Comment by M4nouel** [comment] 2020-07-15 15:22
Ok @vania-pooh , Im on it

**Comment by vania-pooh** [comment] 2020-07-16 16:17
@M4nouel yep, seems to be a good idea. Let's remove these changes from base_2 image.

**Comment by M4nouel** [comment] 2020-07-22 15:17
Hi @vania-pooh ,
(I can't work as fast i would like on this...)
But in the commit above, i implement a (quick) feature that allow to push images built on custom docker registry using shell context variables passed as "named-like" environment variables (e.g ```DOCKER_REGISTRY="my_nexus.local:5000" ./automate_firefox.sh ...```).
I also add a feature that allow to not be asked for push, using the same kind of variables (e.g ```DOCKER_REGISTRY="my_nexus.local:5000" PUSH_ALL="y" ./automate_firefox.sh ...```).
Since we usually use the vnc image, this ```PUSH_ALL``` can't have this values :
* "y" to push all images built
* "n" to push none of them 
* "vnc" to push only vnc tag

Using a Jenkins pipeline like this one : 
```groovy
pipeline {
    agent any
    stages {
        stage('Build and Push') {
            steps {
                script {
                    docker.withRegistry('http://my_nexus.local:5000') {
                        sh '''
                            cd selenium && \
                            DOCKER_REGISTRY="my_nexus.local:5000/" PUSH_ALL="vnc" ./automate_firefox.sh 68.10.0esr+build1-0ubuntu0.18.04.1 1.10.0 68.9 0.24.0 esr
                           '''
                    }
                }
            }
        }
    }
    post {
        always {
            // rm built images
        }
    }
}
```
I was able to build selenoid images and push them on a private docker registry.

If this issue aim to implement a feature that allow to build selenoid images using a json conf file (parsed by jq for exemple), this code can do the work and take us to the implementation of the json conf file stuff.

But i think it would be cool to get the code base more modular by splitting each "automate_...sh" in 3 or 4 scripts by browser, that have the resposability of : 
* Generate the Dockerfiles
* Build the Dockerfiles
* Test the docker image
* And push the docker images

So the "automate_...sh" could call these script and the use of this project would stay as easy as today. 
But the code updates and CI "stages" could be easier to write and clearier to read.

For example, for firefox, all the part dealing with : 
* the base_image to choose, 
* the driver and the firefox version to check and choose... 
* the image generation... 

could be in the script "selenium/firefox/gen_Dockerfile.sh". So that script can produce (and download) all the thing we need to ```docker build``` our self or use the script to build, then the one to test and so on.

What do you think about these 2 ideas ?

**Comment by vania-pooh** [comment] 2020-07-23 07:42
@M4nouel all these scripts are becoming too much complicated. I would then opt for implementing a Golang binary for building images and completely throw away bash stuff.

**Comment by M4nouel** [comment] 2020-07-23 15:52
@vania-pooh  I agree, they are becoming really complicated ! And they need some rework to become clear again.
But re implementing all of this it's a lot of work !
How do you plan to do this ? Will you reuse some code of [Configuration manager](https://github.com/aerokube/cm) ?

**Comment by vania-pooh** [comment] 2020-07-24 04:04
@ruescar are you ok with moving from Bash to Golang? We are now having so many flags and options, that it would be easier to replace all these flags and complicated logic with a binary probably with all Dockerfiles embedded inside the binary (e.g. with [statik](https://github.com/rakyll/statik)).

**Comment by vania-pooh** [comment] 2020-07-27 11:33
@M4nouel @ruescar take a look at this new stuff. https://github.com/vania-pooh/selenoid-images/tree/golang-binary :)

**Comment by M4nouel** [comment] 2020-07-27 16:24
Ah darn ! :)  That looks realy cool !
@vania-pooh  @ruescar , I was working on a "jenkins-able" firefox selenoid-image using modular scripts because we needed it quickly, but @vania-pooh's work seems not far from being completed.

@vania-pooh do you implemented (or plan to implement) : 
* **handling proxy at docker build ?**
* **handling JSON configuration file ?**
* **producing Dockerfile for later build or corporate customization (e.g add policies.json to firefox esr build at once) ?**

One more thing, if I may, could we use a full templating solution to generate the Dockerfiles ? Because the ```RUN``` keywords ended by a ``` || true``` leads to never be warned when the build fails.
For example, I wrote a single multistage Dockerfile (to see all the Layers (optional java, browser, driver)) and used [Jinja](https://github.com/kolypto/j2cli) templating, thus, conditionals commands are carried by the template and processed by Jinja to create a single multistage Dockerfile that fails if a command fails. 
* Here the script that generates the directory ready to ```docker build``` cmd : https://github.com/M4nouel/selenoid-images/blob/modular_scripts/rework/ff/gen_Dockerfile.sh 
Executed like this ```./gen_Dockerfile.sh build_config_apt_esr_example.json``` ([conf file](https://github.com/M4nouel/selenoid-images/blob/modular_scripts/rework/ff/build_config_apt_esr_example.json))
* Here the Dockerfile produced : https://github.com/M4nouel/selenoid-images/blob/modular_scripts/rework/target/firefox/Dockerfile 
* And the template : https://github.com/M4nouel/selenoid-images/blob/modular_scripts/rework/ff/resources/Dockerfile.j2
(I was about to change Jinja for [Gomplate](https://github.com/hairyhenderson/gomplate))

What do you think about this idea ?

**Comment by vania-pooh** [comment] 2020-07-27 17:18
@M4nouel 

1) I think we could use built-in Go templates (very similar to Jinja) for this. Currently I'm just trying to repeat everything we already have.

2) Handling HTTP_PROXY variables is already implemented:
```
HTTP_PROXY=my-proxy.example.com:8080 ./selenoid-images chrome ...
```

3) Custom Docker registry support is implemented by just using `--tag (or -t)` flag that defines full image tag, so you could use it like `--tag registry.example.com/selenium/firefox:77.0 --tag selenoid/firefox:77.0`. Using `--tag` several times will tag image with multiple tags.

4) Also added support for `GITHUB_TOKEN` environment variable to prevent issues with Github API request rate (with token - request rate is slightly bigger).

5) Don't get what do you mean by this: `handling JSON configuration file ?`.

6) All the rest - could be added to the binary. E.g. to copy custom files to image we could add a flag like `--include /path/to/file` and this file will be automatically copied to Docker build directory and then copied to the image.

**Comment by M4nouel** [comment] 2020-07-28 12:37
Ok, great ! Thank you @vania-pooh !

By "```handling JSON configuration file ?```", I meant ```pass a JSON file to the go binary that stores all the parameters we want```; like @conradkirschner asked : 
* browser
* browser_version
* driver_version
* tag
* GITHUB_TOKEN
* skip_tests
* HTTP_PROXY
* HTTPS_PROXY
* ...

**Comment by vania-pooh** [comment] 2020-07-28 12:41
@M4nouel IMHO this is an over-complication. So far as I can understand the main use case is storing and versioning such file under VCS. But what would prevent you from storing an exact command with all flags under the same VCS?

**Comment by M4nouel** [comment] 2020-07-28 14:53
@vania-pooh I was thinking about having a simple and friendly way to use the Go binary without having to think about which param to put behind the Go binary call and which one to put after (e.g ```HTTP_PROXY=my-proxy.example.com:8080 ./selenoid-images chrome ...```), But you're right since most users don't necessarily use all these options !

Can't wait to see the new release !

**Comment by vania-pooh** [comment] 2020-07-28 15:01
@M4nouel ok, let me thoroughly test all these changes and will create a PR then.

**Comment by M4nouel** [comment] 2020-07-28 15:10
ok @vania-pooh , no problem, thanks !

**Comment by ruescar** [comment] 2020-07-30 21:40
@vania-pooh This new Golang implementation sounds like a great idea! 👍  It's true that even simple changes were getting more and more complicated to be done in Bash. I will also test this branch thoroughly and let you know how it looks from my side. And if it still complies with the changes I made that I need.

**Comment by ruescar** [comment] 2020-07-30 22:29
@M4nouel After reading all your points I thought I would share with you some thoughts as I already went through similar things when I started integrating with selenoid-images some time ago. Because some things may be done simpler outside this project while Bash version is still applicable:

-  **Tagging and pushing to your own Docker registry:** 
`echo "n" | ./automate_firefox.sh ... 70.0 ...`
`docker tag  selenoid/firefox:70.0 your_new_tag`
`docker push your_new_tag`

- **RUN keywords ended by a || true leads to never be warned when the build fails:**
True. For example if you try to build a browser image for a version which is not available. Therefore it's recommendable that you don't skip selenoid-container-tests so you can verify the health of that image.

- **Github API request rate:**
I wonder why you need to build browser images so often... as it's unlikely to get more than one browser new version per channel per day. Then when you build it, if you push it to a registry like https://hub.docker.com/u/selenoid or https://hub.docker.com/r/twilio/selenoid where we publish the dev and beta versions, you just need to keep pulling them.
By the way, on the latter Twilio registry you can see instructions on how to inspect the browser and driver contained in the image from docker labels.

However I agree it's a good improvement @vania-pooh to add GITHUB_TOKEN especially for regression testing big changes, and not having to always pass a fixed driver version to prevent hitting the request rate.

And finally regarding having a **JSON config file with the build parameters.**.. @conradkirschner I'm not sure. It still feels more natural to me passing those variable parameters to a script and use Env Vars for constant values such as tokens of config options... the case of browsers.json is different because you are likely to use the same one for quite long time. Although in my case that I build frequent Dev, Beta images, I also had to template browsers.json

**Comment by conradkirschner** [comment] 2020-08-26 20:52
@ruescar I just had the Idea of: 

"Starting Moon, it will read the configuration, build the represpective browser container and make them available in the tests" 

About actually env. variables like Github Token or any other Keys, I totally agree that these should not belong into a config file... 

For shared things like Browser Version, I still see a possibility to sync this somehow. 

(Maybe I miss the scenarios where you build&publish browser images that you actually don't use in moon)


Anyway this new non-bash solution looks promising for building these images,  so maybe it's easy enough ❤️

**Comment by ruescar** [comment] 2020-08-31 18:38
@conradkirschner I'm not a Moon user, I just use Selenoid, so maybe @vania-pooh can clarify better on that.
However my understanding is that when it comes to launching browser containers from browser images, the process of doing it with Moon or just Selenoid (via a config file) is pretty much the same. 
I differentiate two very different steps here:
1. Build Selenoid images and push them to your own Docker images registry (either public or private). As I do here on our public one https://hub.docker.com/r/twilio/selenoid or alternatively just use Selenoid official registry https://hub.docker.com/u/selenoid/ which should also contain non-stable channels soon too when the new CI is implemented.
On this step, former bash scripts or current Go scripts are used to build/push the images.
2. Launch a new browser container in either Selenoid grid or Moon grid on the go from prebuilt images (via config file).

I personally don't see much value in building an image every time you need it (inside Moon or Selenoid) if that's what you mean. This is not only unnecessary but it would also make the process of launching a new browser container very slow.

Regarding "Shared things like Browser Version...", I don't understand what you mean by that.
However if you only call those scripts to build images, and are not planning to change their implementation going forward, either Bash or Go should make no difference to you, since they take pretty much the same arguments.

**Comment by vania-pooh** [comment] 2020-09-26 16:24
I consider this fixed as we migrated to Golang. Feel free to open new issues if something is not yet implemented.

**Closed by vania-pooh** 2020-09-26 16:24 UTC
Labels: new-feature
